---
- hosts: all
  become: true
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes
        
    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: install docker service
      apt: 
       name: docker.io
       state: latest
      notify: start and enable docker service

  handlers:
    - name: start and enable docker service
      service:
        name: docker 
        enabled: yes
        state: started

- hosts: prasta-os1
  become: true
  tasks:
    - name: download and install cephadm pkg
      get_url:
      url: https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm
      dest: /usr/local/bin/cephadm
      mode: '0755'
    
    - name: install ceph tools
      command: cephadm add-repo --release octopus

    - name: import ceph gpg key
      shell: curl https://download.ceph.com/keys/release.asc | gpg --no-default-keyring --keyring /tmp/fix.gpg --import - && gpg --no-default-keyring --keyring /tmp/fix.gpg --export > /etc/apt/trusted.gpg.d/ceph.release.gpg && rm /tmp/fix.gpg
      args:
        warn: false

    - name: Update apt-get repo and cache
      apt: update_cache=yes

    - name: install ceph-common pkg
      command: cephadm install ceph-common
  